# hybrid_demucs.sub
# My HTCondor submit file
docker_image = rselagam/ndns:v53_cuda12.4.0_esong32
universe = docker
   
executable = hybrid_demucs.sh
log = hybrid_demucs_$(Cluster).log
error = hybrid_demucs_$(Cluster).err
output = hybrid_demucs_$(Cluster).out
   
transfer_input_files = hybrid_demucs_tutorial.py
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
   
# Tell HTCondor requirements (e.g., operating system) your job needs, 
# what amount of compute resources each job will need on the computer where it runs.
request_cpus = 1
request_memory = 36GB
request_disk = 180GB
   
# Tell HTCondor to run 1 instance of our job:
queue 1