# train.sub
docker_image = rselagam/ndns:v52_cuda12.4.0_selagamsetty
universe = docker

# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = polyphonic_cmd.sh
log = $(Cluster)_$(Process).log
output = $(Cluster)_$(Process).out
error = $(Cluster)_$(Process).err

# Specify that HTCondor should transfer files to and from the
#  computer where each job runs.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
want_io_proxy = true
batch_name = "polyphonic_decomp"

+WantGPULab = true
+GPUJobLength = "short"
request_gpus = 1
request_cpus = 1
request_memory = 64GB
request_disk = 650GB
requirements = (Target.CUDADriverVersion >= 12.4 && Target.CUDACapability >= 8.0)

# Tell HTCondor to run 1 instances of our job:
queue 1 
