# train_A100_40GB.sub
#
# Provide HTCondor with the name of the Docker container
docker_image = rselagam/ndns:v51_cuda12.4.0_selagamsetty
universe = docker

executable = ndns_cmd.sh
log = A100_40GB_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(noiseEndIdx)_$(Cluster).log
output = A100_40GB_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(noiseEndIdx)_$(Cluster).out
error = A100_40GB_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(noiseEndIdx)_$(Cluster).err

# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to use.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
arguments = $(subject) $(channel) $(speech) $(noiseStartIdx) $(noiseEndIdx) $(batchSize) $(workers) $(prefetchFactor) $(saveProfile)
max_idle = 10
want_io_proxy = true
#TODO should change back to -15 when done with testing
priority = -15
batch_name = "A100_40GB_medium_1249"

+WantGPULab = true
+GPUJobLength = "medium"

request_gpus = 1
request_cpus = 1
request_memory = 36GB
request_disk = 180GB
require_gpus = (Capability == 8.0) && (DriverVersion >= 12.4)
requirements = (HasCHTCStaging == True) && (CUDAGlobalMemoryMb > 30000) && (CUDAGlobalMemoryMb < 50000)

# Tell HTCondor to run 1 instances of our job:
queue subject,channel,speech,noiseStartIdx,noiseEndIdx,batchSize,workers,prefetchFactor,saveProfile from configs_A100_40GB.txt 
