# train_H100_medium.sub
#
# Provide HTCondor with the name of the Docker container
docker_image = rselagam/ndns:v51_cuda12.4.0_selagamsetty
universe = docker

executable = ndns_cmd.sh
log = H100M_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(numNoiseSims)_$(Cluster).log
output = H100M_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(numNoiseSims)_$(Cluster).out
error = H100M_$(subject)_$(channel)_$(speech)_$(noiseStartIdx)_$(numNoiseSims)_$(Cluster).err

# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to use.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT
arguments = $(subject) $(channel) $(speech) $(noiseStartIdx) $(numNoiseSims)
max_idle = 10
want_io_proxy = true
#TODO should change back to -15 when done with testing
priority = -15
batch_name = "H100_medium_925_950"

+WantGPULab = true
+GPUJobLength = "medium"

request_gpus = 1
request_cpus = 4
request_memory = 40GB
request_disk = 200GB
require_gpus = (Capability == 9.0) && (DriverVersion >= 12.4)
requirements = (HasCHTCStaging == True)

# Tell HTCondor to run 1 instances of our job:
queue subject,channel,speech,noiseStartIdx,numNoiseSims from configs_H100_medium.txt 
