# train.sub
#
# Provide HTCondor with the name of the Docker container
docker_image = rselagam/ndns:v51_cuda12.4.0_selagamsetty
universe = docker

# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = ndns_cmd.sh
log = $(Cluster)_$(epoch).log
output = $(Cluster)_$(epoch).out
error = $(Cluster)_$(epoch).err
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines *would* be
#  used if there were any other files needed for the executable to use.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
arguments = $(epoch)
max_idle = 10
want_io_proxy = true
priority = -15

+WantGPULab = true
+GPUJobLength = "medium"

request_gpus = 1
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 1
request_memory = 64GB
request_disk = 650GB
#require_gpus = (Capability >= 8.0) && (Capability < 9) && (DriverVersion > 12.1)
# Only target the L40s since the A100s are slow
require_gpus = (Capability > 8.0) && (Capability < 9) && (DriverVersion > 12.1)
requirements = (HasCHTCStaging == True) && (Machine != "gpu2003.chtc.wisc.edu") && (Machine != "gpu4001.chtc.wisc.edu") && (Machine != "txie-dsigpu4000.chtc.wisc.edu")

# Tell HTCondor to run 1 instances of our job:
queue epoch from epochs.txt 
